# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
      
resources:
  containers:
  - container: maven3
    image: maven:3-jdk-8

container: maven3
steps:
- task: Maven@3
    inputs: 
       mavenPomFile: 'example/pom.xml' 
       goals: 'package deploy' 
       mavenAuthenticateFeed: true
